"""
LangGraph State Definition

Defines the shared state structure for the multi-agent supply chain system.
This state is passed between agents and accumulates information as the
cognitive workflow processes alerts and makes decisions.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Annotated, Any, Dict, List, Literal, Optional, TypedDict, Union

try:
    from langchain_core.messages import BaseMessage
    from langgraph.graph import add_messages
    HAS_LANGGRAPH = True
except ImportError:
    HAS_LANGGRAPH = False
    # Fallback when langgraph is not installed
    BaseMessage = Dict[str, Any]  # Use dict as message type
    # Fallback reducer that just returns the second list (simple append)
    def add_messages(left: List, right: List) -> List:
        """Fallback message reducer."""
        if isinstance(left, list) and isinstance(right, list):
            return left + right
        return [left, right] if not isinstance(left, list) else left + [right]



class AlertSeverity(str, Enum):
    """Severity levels for supply chain alerts."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class AlertType(str, Enum):
    """Types of supply chain alerts that trigger cognitive processing."""
    DEMAND_SPIKE = "demand_spike"
    DEMAND_DROP = "demand_drop"
    INVENTORY_LOW = "inventory_low"
    INVENTORY_EXCESS = "inventory_excess"
    SUPPLY_DISRUPTION = "supply_disruption"
    LEAD_TIME_CHANGE = "lead_time_change"
    BULLWHIP_DETECTED = "bullwhip_detected"
    FORECAST_DEVIATION = "forecast_deviation"
    STOCKOUT = "stockout"
    CAPACITY_CONSTRAINT = "capacity_constraint"


class RecommendationType(str, Enum):
    """Types of recommendations agents can make."""
    ADJUST_REORDER_POINT = "adjust_reorder_point"
    ADJUST_ORDER_QUANTITY = "adjust_order_quantity"
    ADJUST_SAFETY_STOCK = "adjust_safety_stock"
    EXPEDITE_ORDER = "expedite_order"
    CHANGE_SUPPLIER = "change_supplier"
    INCREASE_CAPACITY = "increase_capacity"
    REDISTRIBUTE_INVENTORY = "redistribute_inventory"
    NO_ACTION = "no_action"


@dataclass
class Alert:
    """
    Represents a supply chain alert that requires cognitive processing.
    
    Alerts are generated by the simulation when thresholds are crossed
    or anomalies are detected.
    """
    alert_type: AlertType
    severity: AlertSeverity
    affected_nodes: List[int]
    details: Dict[str, Any]
    timestamp: datetime = field(default_factory=datetime.now)
    alert_id: Optional[str] = None
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert alert to dictionary for state storage."""
        return {
            "alert_type": self.alert_type.value,
            "severity": self.severity.value,
            "affected_nodes": self.affected_nodes,
            "details": self.details,
            "timestamp": self.timestamp.isoformat(),
            "alert_id": self.alert_id,
        }
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "Alert":
        """Create alert from dictionary."""
        return cls(
            alert_type=AlertType(data["alert_type"]),
            severity=AlertSeverity(data["severity"]),
            affected_nodes=data["affected_nodes"],
            details=data["details"],
            timestamp=datetime.fromisoformat(data.get("timestamp", datetime.now().isoformat())),
            alert_id=data.get("alert_id"),
        )


@dataclass
class Recommendation:
    """
    Represents a recommendation from a cognitive agent.
    
    Recommendations may require human approval before execution.
    """
    recommendation_type: RecommendationType
    target_nodes: List[int]
    parameters: Dict[str, Any]
    reasoning: str
    confidence: float  # 0-1
    source_agent: str  # supervisor, analyst, negotiator
    requires_approval: bool = True
    approved: Optional[bool] = None
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert recommendation to dictionary."""
        return {
            "recommendation_type": self.recommendation_type.value,
            "target_nodes": self.target_nodes,
            "parameters": self.parameters,
            "reasoning": self.reasoning,
            "confidence": self.confidence,
            "source_agent": self.source_agent,
            "requires_approval": self.requires_approval,
            "approved": self.approved,
        }
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "Recommendation":
        """Create recommendation from dictionary."""
        return cls(
            recommendation_type=RecommendationType(data["recommendation_type"]),
            target_nodes=data["target_nodes"],
            parameters=data["parameters"],
            reasoning=data["reasoning"],
            confidence=data["confidence"],
            source_agent=data["source_agent"],
            requires_approval=data.get("requires_approval", True),
            approved=data.get("approved"),
        )


@dataclass
class SimulationSnapshot:
    """
    Snapshot of the current simulation state.
    
    Provides context for cognitive agents to make decisions.
    """
    current_step: int
    total_inventory: float
    bullwhip_ratio: float
    node_inventories: Dict[int, float]
    node_pending_orders: Dict[int, float]
    recent_demands: Dict[int, List[float]]  # Last N demands per node
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert snapshot to dictionary."""
        return {
            "current_step": self.current_step,
            "total_inventory": self.total_inventory,
            "bullwhip_ratio": self.bullwhip_ratio,
            "node_inventories": self.node_inventories,
            "node_pending_orders": self.node_pending_orders,
            "recent_demands": self.recent_demands,
        }


@dataclass
class ForecastData:
    """
    Container for demand forecast data from the GNN model.
    """
    node_id: int
    predictions: List[float]
    confidence_lower: Optional[List[float]] = None
    confidence_upper: Optional[List[float]] = None
    horizon: int = 7
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert forecast to dictionary."""
        return {
            "node_id": self.node_id,
            "predictions": self.predictions,
            "confidence_lower": self.confidence_lower,
            "confidence_upper": self.confidence_upper,
            "horizon": self.horizon,
        }


# Agent routing options
AgentRoute = Literal["supervisor", "analyst", "negotiator", "tools", "human", "end"]


class SupplyChainState(TypedDict):
    """
    Shared state for supply chain cognitive agents.
    
    This TypedDict defines the structure of state passed through
    the LangGraph workflow. It accumulates information as agents
    process alerts and make decisions.
    
    Attributes:
        messages: Conversation history with add_messages annotation
                  for automatic aggregation across agent turns
        current_alert: The active alert being processed (dict form)
        simulation_state: Snapshot of current simulation state
        forecasts: Recent demand forecasts keyed by node_id
        recommendations: List of agent recommendations pending approval
        human_feedback: Optional feedback from human operators
        next_agent: Which agent should act next in the workflow
        analysis_results: Results from analyst agent
        negotiation_results: Results from negotiator agent
        iteration_count: Number of agent iterations (for loop prevention)
        error: Any error message from processing
    """
    messages: Annotated[List[BaseMessage], add_messages]
    current_alert: Optional[Dict[str, Any]]
    simulation_state: Dict[str, Any]
    forecasts: Dict[int, Dict[str, Any]]  # node_id -> ForecastData as dict
    recommendations: List[Dict[str, Any]]  # List of Recommendation dicts
    human_feedback: Optional[str]
    next_agent: AgentRoute
    analysis_results: Optional[Dict[str, Any]]
    negotiation_results: Optional[Dict[str, Any]]
    iteration_count: int
    error: Optional[str]


def create_initial_state(
    alert: Optional[Alert] = None,
    simulation_snapshot: Optional[SimulationSnapshot] = None,
) -> SupplyChainState:
    """
    Create an initial state for the cognitive workflow.
    
    Args:
        alert: Optional alert to process
        simulation_snapshot: Optional simulation state snapshot
        
    Returns:
        Initial SupplyChainState ready for workflow execution
    """
    return SupplyChainState(
        messages=[],
        current_alert=alert.to_dict() if alert else None,
        simulation_state=simulation_snapshot.to_dict() if simulation_snapshot else {},
        forecasts={},
        recommendations=[],
        human_feedback=None,
        next_agent="supervisor",
        analysis_results=None,
        negotiation_results=None,
        iteration_count=0,
        error=None,
    )


def add_recommendation(
    state: SupplyChainState,
    recommendation: Recommendation
) -> SupplyChainState:
    """
    Add a recommendation to the state.
    
    Args:
        state: Current state
        recommendation: Recommendation to add
        
    Returns:
        Updated state with new recommendation
    """
    new_recs = state["recommendations"].copy()
    new_recs.append(recommendation.to_dict())
    return {**state, "recommendations": new_recs}


def add_forecast(
    state: SupplyChainState,
    forecast: ForecastData
) -> SupplyChainState:
    """
    Add a forecast to the state.
    
    Args:
        state: Current state
        forecast: Forecast data to add
        
    Returns:
        Updated state with new forecast
    """
    new_forecasts = state["forecasts"].copy()
    new_forecasts[forecast.node_id] = forecast.to_dict()
    return {**state, "forecasts": new_forecasts}


# Threshold constants for alert generation
ALERT_THRESHOLDS = {
    "demand_spike_factor": 1.5,  # 50% increase triggers spike
    "demand_drop_factor": 0.5,   # 50% decrease triggers drop
    "low_inventory_ratio": 0.5,  # Below 50% of reorder point
    "excess_inventory_ratio": 2.0,  # Above 200% of order-up-to
    "bullwhip_threshold": 2.0,   # Bullwhip ratio above 2.0
    "forecast_deviation_pct": 20.0,  # 20% deviation from forecast
    "critical_escalation_nodes": 3,  # Escalate if > 3 nodes affected
}


# Agent decision thresholds
DECISION_THRESHOLDS = {
    "auto_approve_confidence": 0.9,  # Auto-approve if confidence > 90%
    "require_analyst_change_pct": 20.0,  # Require analyst for > 20% changes
    "max_iterations": 10,  # Maximum agent iterations per alert
}
